# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_cognatenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsubset',
            name='words',
            field=models.ManyToManyField(blank=True, to='lexicon.Word'),
        ),
    ]
