# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_concepticon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepticon',
            name='ontologicalcategory',
            field=models.CharField(blank=True, db_index=True, help_text=b'Ontological Category', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='concepticon',
            name='semanticfield',
            field=models.CharField(blank=True, db_index=True, help_text=b'Semantic Field', max_length=32, null=True),
        ),
    ]
