# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronoun',
            name='entries',
            field=models.ManyToManyField(blank=True, to='lexicon.Lexicon'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='relationships',
            field=models.ManyToManyField(blank=True, to='pronouns.Relationship'),
        ),
    ]
